### ISSUE TITLE
The first scroll-to point is weird

### ISSUE THREAD

**Issue by brianboyer** [nprapps/syria#120] opened 2015-02-13 15:51 UTC
![screen shot 2015-02-13 at 10 51 32 am](https://cloud.githubusercontent.com/assets/68644/6190216/51b6fbb2-b36e-11e4-81b4-036c92f20e4a.png)

**Comment by eads** [comment] 2015-02-13 18:41
Dupe of #96, fixed

**Closed as completed by eads** 2015-02-13 18:41 UTC
